// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpAyx8ydWO_cEerr4HUXh9y3adWVGwd2s',
    appId: '1:335390254249:android:3523de28ab0a9912d875b8',
    messagingSenderId: '335390254249',
    projectId: 'projeto-cm-d81c9',
    databaseURL: 'https://projeto-cm-d81c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projeto-cm-d81c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALU-U5IIjsW2ANT6dk0u_tFRJ5XwgWI38',
    appId: '1:335390254249:ios:d54fa30ff5b069e7d875b8',
    messagingSenderId: '335390254249',
    projectId: 'projeto-cm-d81c9',
    databaseURL: 'https://projeto-cm-d81c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projeto-cm-d81c9.appspot.com',
    iosBundleId: 'com.example.flutterApplicationProjetoCm',
  );
}
