name: flutter_application_projeto_cm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3 
  audioplayers: ^6.0.0
  light: ^3.0.1
  firebase_auth: ^5.1.0
  local_auth: ^2.1.6
  file_selector: ^1.0.3
  firebase_core: ^3.1.0
  sensors_plus: ^5.0.1
  awesome_notifications: ^0.9.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/hats/hat_section.png
    - assets/hats/hat1.png
    - assets/hats/hat2.png
    - assets/hats/hat3.png
    - assets/hats/hat4.png
    - assets/hats/hat5.png
    - assets/hats/hat6.png
    - assets/colors/color_section.png
    - assets/colors/color_white.png
    - assets/colors/color_pink.png
    - assets/colors/color_light_pink.png
    - assets/colors/color_yellow.png
    - assets/colors/color_green.png
    - assets/colors/color_blue.png
    - assets/backgrounds/background_section.png
    - assets/backgrounds/bg1.png
    - assets/backgrounds/bg2.png
    - assets/backgrounds/bg3.png
    - assets/backgrounds/bg4.png
    - assets/backgrounds/bg5.png
    - assets/backgrounds/bg6.png
    - assets/backgrounds/bg7.png
    - assets/backgrounds/bg8.png
    - assets/backgrounds/bg9.png
    - assets/backgrounds/bg10.png
    - assets/backgrounds/bg11.png
    - assets/backgrounds/bg12.png
    - assets/windows/window_section.png
    - assets/windows/window1.png
    - assets/windows/window2.png
    - assets/windows/window3.png
    - assets/coin.png
    - assets/quiz.png
    - assets/clean_house.png
    - assets/memory_game.png
    - assets/color_game.png
    - assets/game_controller.png
    - assets/customize_icon.png
    - assets/lollipop_icon.png
    - assets/shower_icon.png
    - assets/shop_icon.png
    - assets/map_icon.png
    - assets/settings_icon.png
    - assets/profile_icon.png
    - assets/ghost.png
    - assets/sound/music.mp3
    - assets/sound/click_sound.mp3
    - assets/sound/buy_sound.mp3
    - assets/sound/lollipop_licking.mp3
    - assets/sound/clock.mp3
    - assets/sound/level_passed.mp3
    - assets/sound/level_failed.mp3
    - assets/spooky_haunted_house.png
    - assets/cobweb.png
    - assets/dust.png
    - assets/cleaning_tool_1.png
    - assets/cleaning_tool_2.png
    - assets/image.png
    - assets/imagee.png
    - assets/logo.png
    - assets/login.png
    - assets/Profile_Ghost.png
    - assets/hidden.png
    - assets/sleeping.png
    - assets/awake.png
